<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login || POS</title>
    @vite(['resources/css/app.css','resources/js/app.js'])
    <style>
        body {
            background: url('/files/background.jpg');
            background-size: cover;
        }

        /* Glassmorphism card effect */
        .card {
            backdrop-filter: blur(5px) saturate(150%);
            -webkit-backdrop-filter: blur(10px) saturate(150%);
            background-color: rgba(255, 255, 255, 0.4);
        }

        /* Generated by https://generator.ui.glass/ */
    </style>
</head>

<body>
    <div
        class="flex flex-col items-center justify-center px-6 py-8 mx-auto min-h-screen">
        <!-- Alert Popup -->
        @if (session('alert'))
        <div
            id="alert-popup"
            class="fixed top-20 right-0 transform translate-x-full flex items-center p-4 mb-4 text-green-600 rounded-lg bg-green-200 w-max transition-transform duration-500 z-20"
            role="alert">
            <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
            </svg>
            <div class="ms-3 text-sm font-medium mr-20">
                {{ session('alert') ?? 'Alert Message' }}
            </div>
            <button type="button" id="close-alert" class="ms-auto -mx-1.5 -my-1.5 hover:bg-green-100 text-green-500 rounded-lg focus:ring-2 focus:ring-green-400 p-1.5 bg-green-200 inline-flex items-center justify-center h-8 w-8" aria-label="Close">
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                </svg>
            </button>
        </div>
        @endif
        <!-- Alert Popup End -->
        <div
            class="card w-full rounded-lg md:mt-0 sm:max-w-md xl:p-0">
            <div
                class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1
                    class="text-xl font-bold leading-tight tracking-tight text-center text-gray-900 md:text-2xl">
                    Sign in to your account
                </h1>
                <!-- ERROR FIELD -->
                @if ($errors->any())
                @foreach ($errors->all() as $error)
                <div class="flex items-center p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50" role="alert">
                    <div>
                        <span class="font-medium">Error!</span> {{ $error }}
                    </div>
                </div>
                @endforeach
                @endif
                <!-- LOG IN FORM -->
                <form
                    class="space-y-4 md:space-y-6"
                    action="/login"
                    method="POST">
                    @csrf
                    <div>
                        <label
                            for="email"
                            class="block mb-2 text-sm font-medium text-gray-900">
                            Your email
                        </label>
                        <input
                            type="email"
                            name="email"
                            id="email"
                            class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                            placeholder="name@company.com"
                            required>
                    </div>
                    <div>
                        <label
                            for="password"
                            class="block mb-2 text-sm font-medium text-gray-900">
                            Password
                        </label>
                        <input
                            type="password"
                            name="password"
                            id="password"
                            placeholder="••••••••"
                            class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                            required>
                    </div>
                    <div
                        class="text-right">
                        <a
                            href="#"
                            class="text-sm font-medium text-primary-600 hover:underline">
                            Forgot password?
                        </a>
                    </div>
                    <button
                        type="submit"
                        class="mt-4 w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                        Sign in
                    </button>
                    <p
                        class="text-center text-sm font-light text-gray-700">
                        Don't have an account yet?<a
                            href="{{ route('signup') }}"
                            class="font-medium text-primary-600 hover:underline">
                            Sign up
                        </a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</body>

</html>